"""update_score_table

Revision ID: 2a203a2c29c6
Revises: af97733672a9
Create Date: 2025-11-06 19:16:57.110794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a203a2c29c6'
down_revision: Union[str, Sequence[str], None] = 'af97733672a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('mode', sa.String(length=10), nullable=False))
    op.add_column('scores', sa.Column('mode_value', sa.Integer(), nullable=False))
    op.add_column('scores', sa.Column('cps', sa.Float(), nullable=False))
    op.add_column('scores', sa.Column('total_clicks', sa.Integer(), nullable=False))
    op.add_column('scores', sa.Column('correct_clicks', sa.Integer(), nullable=False))
    op.add_column('scores', sa.Column('duration', sa.Float(), nullable=False))
    op.add_column('scores', sa.Column('accuracy', sa.Float(), nullable=False))
    op.add_column('scores', sa.Column('consistency', sa.Float(), nullable=True))
    op.add_column('scores', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('scores', 'points')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('scores', 'created_at')
    op.drop_column('scores', 'consistency')
    op.drop_column('scores', 'accuracy')
    op.drop_column('scores', 'duration')
    op.drop_column('scores', 'correct_clicks')
    op.drop_column('scores', 'total_clicks')
    op.drop_column('scores', 'cps')
    op.drop_column('scores', 'mode_value')
    op.drop_column('scores', 'mode')
    # ### end Alembic commands ###
